// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAfJN77PSi5tCm6vNG-YOu8DfJGeCyWCsc',
    appId: '1:175130783468:web:539bfd9850dae3987abfc9',
    messagingSenderId: '175130783468',
    projectId: 'fruit-hub-1452b',
    authDomain: 'fruit-hub-1452b.firebaseapp.com',
    storageBucket: 'fruit-hub-1452b.firebasestorage.app',
    measurementId: 'G-0RLYG32GLK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBvyHnLEBKShNUCnbLhR4UW_vKxgPdSu3U',
    appId: '1:175130783468:android:1a4e3d72ffe44a607abfc9',
    messagingSenderId: '175130783468',
    projectId: 'fruit-hub-1452b',
    storageBucket: 'fruit-hub-1452b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAeJMWn_fi_RIR4-rcmkFb74Xlx5MzyTjk',
    appId: '1:175130783468:ios:a159ee9bcfbd01aa7abfc9',
    messagingSenderId: '175130783468',
    projectId: 'fruit-hub-1452b',
    storageBucket: 'fruit-hub-1452b.firebasestorage.app',
    iosBundleId: 'com.example.eCommerce',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAeJMWn_fi_RIR4-rcmkFb74Xlx5MzyTjk',
    appId: '1:175130783468:ios:a159ee9bcfbd01aa7abfc9',
    messagingSenderId: '175130783468',
    projectId: 'fruit-hub-1452b',
    storageBucket: 'fruit-hub-1452b.firebasestorage.app',
    iosBundleId: 'com.example.eCommerce',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAfJN77PSi5tCm6vNG-YOu8DfJGeCyWCsc',
    appId: '1:175130783468:web:cf1c5dfdacaaeb5f7abfc9',
    messagingSenderId: '175130783468',
    projectId: 'fruit-hub-1452b',
    authDomain: 'fruit-hub-1452b.firebaseapp.com',
    storageBucket: 'fruit-hub-1452b.firebasestorage.app',
    measurementId: 'G-0QXZQW30BV',
  );
}
